//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


Vote = function(args) {
  this.Name = null;
  this.Place = null;
  if (args) {
    if (args.Name !== undefined) {
      this.Name = args.Name;
    }
    if (args.Place !== undefined) {
      this.Place = args.Place;
    }
  }
};
Vote.prototype = {};
Vote.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.Name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.Place = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Vote.prototype.write = function(output) {
  output.writeStructBegin('Vote');
  if (this.Name !== null && this.Name !== undefined) {
    output.writeFieldBegin('Name', Thrift.Type.STRING, 1);
    output.writeString(this.Name);
    output.writeFieldEnd();
  }
  if (this.Place !== null && this.Place !== undefined) {
    output.writeFieldBegin('Place', Thrift.Type.STRING, 2);
    output.writeString(this.Place);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AlreadyVotedException = function(args) {
};
Thrift.inherits(AlreadyVotedException, Thrift.TException);
AlreadyVotedException.prototype.name = 'AlreadyVotedException';
AlreadyVotedException.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AlreadyVotedException.prototype.write = function(output) {
  output.writeStructBegin('AlreadyVotedException');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

