//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

LunchService_PlaceVote_args = function(args) {
  this.vote = null;
  if (args) {
    if (args.vote !== undefined) {
      this.vote = args.vote;
    }
  }
};
LunchService_PlaceVote_args.prototype = {};
LunchService_PlaceVote_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.vote = new Vote();
        this.vote.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LunchService_PlaceVote_args.prototype.write = function(output) {
  output.writeStructBegin('LunchService_PlaceVote_args');
  if (this.vote !== null && this.vote !== undefined) {
    output.writeFieldBegin('vote', Thrift.Type.STRUCT, 1);
    this.vote.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LunchService_PlaceVote_result = function(args) {
};
LunchService_PlaceVote_result.prototype = {};
LunchService_PlaceVote_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LunchService_PlaceVote_result.prototype.write = function(output) {
  output.writeStructBegin('LunchService_PlaceVote_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LunchService_GetSuggestions_args = function(args) {
};
LunchService_GetSuggestions_args.prototype = {};
LunchService_GetSuggestions_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LunchService_GetSuggestions_args.prototype.write = function(output) {
  output.writeStructBegin('LunchService_GetSuggestions_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LunchService_GetSuggestions_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
LunchService_GetSuggestions_result.prototype = {};
LunchService_GetSuggestions_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readString().value;
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LunchService_GetSuggestions_result.prototype.write = function(output) {
  output.writeStructBegin('LunchService_GetSuggestions_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRING, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        output.writeString(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LunchService_MakeDecision_args = function(args) {
};
LunchService_MakeDecision_args.prototype = {};
LunchService_MakeDecision_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LunchService_MakeDecision_args.prototype.write = function(output) {
  output.writeStructBegin('LunchService_MakeDecision_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LunchService_MakeDecision_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
LunchService_MakeDecision_result.prototype = {};
LunchService_MakeDecision_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

LunchService_MakeDecision_result.prototype.write = function(output) {
  output.writeStructBegin('LunchService_MakeDecision_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

LunchServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
LunchServiceClient.prototype = {};
LunchServiceClient.prototype.PlaceVote = function(vote) {
  this.send_PlaceVote(vote);
  this.recv_PlaceVote();
};

LunchServiceClient.prototype.send_PlaceVote = function(vote) {
  this.output.writeMessageBegin('PlaceVote', Thrift.MessageType.CALL, this.seqid);
  var args = new LunchService_PlaceVote_args();
  args.vote = vote;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush();
};

LunchServiceClient.prototype.recv_PlaceVote = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new LunchService_PlaceVote_result();
  result.read(this.input);
  this.input.readMessageEnd();

  return;
};
LunchServiceClient.prototype.GetSuggestions = function() {
  this.send_GetSuggestions();
  return this.recv_GetSuggestions();
};

LunchServiceClient.prototype.send_GetSuggestions = function() {
  this.output.writeMessageBegin('GetSuggestions', Thrift.MessageType.CALL, this.seqid);
  var args = new LunchService_GetSuggestions_args();
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush();
};

LunchServiceClient.prototype.recv_GetSuggestions = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new LunchService_GetSuggestions_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'GetSuggestions failed: unknown result';
};
LunchServiceClient.prototype.MakeDecision = function() {
  this.send_MakeDecision();
  return this.recv_MakeDecision();
};

LunchServiceClient.prototype.send_MakeDecision = function() {
  this.output.writeMessageBegin('MakeDecision', Thrift.MessageType.CALL, this.seqid);
  var args = new LunchService_MakeDecision_args();
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush();
};

LunchServiceClient.prototype.recv_MakeDecision = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new LunchService_MakeDecision_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'MakeDecision failed: unknown result';
};
